apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: resumes
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: jobs-app
spec:
  partitions: {{ .Values.kafkaTopics.resumes.partitions }}
  replicas: {{ .Values.kafkaTopics.resumes.replicas }}
  topicName: resumes
