# loader service
apiVersion: v1
kind: Service
metadata:
  name: loader
  labels:
    app: loader
spec:
  ports:
    - port: 50051
      name: grpc
  selector:
    app: loader
---
# Loader deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loader
spec:
  replicas: {{ .Values.loader.replicas }}
  selector:
    matchLabels:
      app: loader
  template:
    metadata:
      labels:
        app: loader
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command: ['sh', '-c', 'until nc -zv jobs-app-kafka-brokers.{{ .Release.Namespace }}.svc.cluster.local 9092; do echo waiting for kafka; sleep 10; done']
      containers:
        - name: loader
          image: {{ include "jobs-app.image" .Values.loader.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: KAFKA_HOST
              value: jobs-app-kafka-brokers.{{ .Release.Namespace }}.svc.cluster.local:9092
            - name: DEBUG
              value: "{{ .Values.debug}}"
            - name: ENABLE_TRACING
              value: "{{ .Values.tracing.enabled }}"
            - name: LOG_SPANS
              value: "{{ .Values.tracing.logSpans }}"
            - name: OTL_EXPORTER_ENABLED
              value: "{{ .Values.tracing.otlpExporterEnabled }}"
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.tracing.otlpExporterHTTPEndpoint }}"
          resources:
            {{- toYaml .Values.loader.resources | nindent 12 }}
