{{ if .Values.networkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: zookeeper
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:name: strimzi-cluster-operator
        - matchLabels:
            k8s:app.kubernetes.io/name: entity-operator
        - matchLabels:
            k8s:app.kubernetes.io/name: kafka
      toPorts:
        - ports:
            - port: "2181"
              protocol: TCP
  egress:
    - {}
{{- end }}
